### ISSUE TITLE
Make editable by all?

### ISSUE THREAD

**Issue by mapsandapps** [codeforatlanta/open-data#15]
Consider moving this to a google doc or somewhere where anyone can edit it without needing to be a member of the hack nighters github group.

**Comment by bbrewington** [comment]
Great idea!

Not sure if Code For Atlanta has a Google account, but I started this on my own google drive.  Feel free to tweak it or copy+move somewhere else -
 https://docs.google.com/spreadsheets/d/1bvD9meJgMqLywdoiGwe3f93sw1IVI_ZRjWSuCLSebZo/edit?usp=sharing

It might be good to sign up for notifications on the sheet (Tools --> notification rules) to keep up with it

**Comment by luigi** [comment]
I'd like to keep some sort of barrier to participate on this. While we're intentionally maintaining a liberal interpretation of open data, I've seen people in the past think that scanned PDFs and login-required databases qualify just because they come from the government and they're online. When we crowdsourced the [city open data census in 2014](http://us-city.census.okfn.org/place/atlanta), we made Atlanta look much better than it really is because we didn't properly coach the participants into correctly identifying open data.

Beyond being added to the hack nighters group, we can also ask for contributions via Pull Request. That way, someone who wants to contribute isn't blocked. Maybe we should make "How do I contribute"? instructions explicit in README.md, or add CONTRIBUTE.md to the repo.

**Comment by mapsandapps** [comment]
I just really wanted to make this open to people who have no idea what a PR is or how to do one (editing the README directly is simple; a PR is not). What about a google doc set to allow people to make suggestions but not directly edit?

**Comment by luigi** [comment]
I like that. :+1:
